# Generated by Django 6.0.5 on 2026-05-20 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plagiarism', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plagiarismreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_plagiarism_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plagiarismreport',
            name='submission_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_reports_as_a', to='submissions.answer'),
        ),
        migrations.AddField(
            model_name='plagiarismreport',
            name='submission_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_reports_as_b', to='submissions.answer'),
        ),
        migrations.AddIndex(
            model_name='plagiarismreport',
            index=models.Index(fields=['submission_a', 'submission_b'], name='plagiarism__submiss_0902bf_idx'),
        ),
        migrations.AddIndex(
            model_name='plagiarismreport',
            index=models.Index(fields=['flagged', 'created_at'], name='plagiarism__flagged_1438b2_idx'),
        ),
        migrations.AddIndex(
            model_name='plagiarismreport',
            index=models.Index(fields=['review_status', 'created_at'], name='plagiarism__review__238dd2_idx'),
        ),
        migrations.AddConstraint(
            model_name='plagiarismreport',
            constraint=models.CheckConstraint(condition=models.Q(('submission_a', models.F('submission_b')), _negated=True), name='plagiarism_report_no_self_compare'),
        ),
        migrations.AddConstraint(
            model_name='plagiarismreport',
            constraint=models.UniqueConstraint(fields=('submission_a', 'submission_b'), name='unique_plagiarism_report_pair'),
        ),
    ]
