# Generated by Django 6.0.5 on 2026-05-20 17:23

import ckeditor_uploader.fields
import django.core.validators
import src.apps.common.utils.files.images
import src.apps.common.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='task_videos/')),
                ('image', models.ImageField(blank=True, null=True, upload_to=src.apps.common.utils.files.images.unique_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), src.apps.common.utils.validators.validate_image_size])),
                ('file', models.FileField(blank=True, null=True, upload_to='task_files/')),
                ('enable_context_menu_for_students', models.BooleanField(default=True)),
                ('allow_resubmitting_task', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'Tasks',
                'base_manager_name': 'objects',
            },
        ),
    ]
