# Generated by Django 6.0.5 on 2026-05-20 17:23

import django.db.models.deletion
import src.apps.common.utils.files.files
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to=src.apps.common.utils.files.files.unique_file_path)),
                ('original_name', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('in_review', 'In review'), ('approved', 'Approved'), ('have_flaws', 'Have Flaws'), ('rejected', 'Rejected')], default='in_review', max_length=20)),
                ('plagiarism_status', models.CharField(choices=[('pending_analysis', 'Pending analysis'), ('analyzed', 'Analyzed'), ('failed', 'Failed')], default='pending_analysis', max_length=32)),
                ('extracted_text', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assignments.task')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'db_table': 'Answers',
            },
        ),
    ]
