create table public."CodeEmail"
(
    id          bigint generated by default as identity
        primary key,
    code        varchar(10)              not null,
    email       varchar(200)             not null,
    expire_date timestamp with time zone not null
);

create table public."Users"
(
    id                bigint generated by default as identity
        primary key,
    password          varchar(128)             not null,
    last_login        timestamp with time zone,
    is_superuser      boolean                  not null,
    first_name        varchar(150)             not null,
    is_staff          boolean                  not null,
    is_active         boolean                  not null,
    date_joined       timestamp with time zone not null,
    email             varchar(254)             not null
        unique,
    last_name         varchar(100),
    google_id         varchar(50)
        unique,
    email_verified    boolean                  not null,
    must_set_password boolean                  not null,
    mfa_enabled       boolean                  not null,
    role              varchar(20)              not null,
    is_deleted        boolean                  not null
);

create table public."Users_groups"
(
    id       bigint generated by default as identity
        primary key,
    user_id  bigint  not null
        constraint "Users_groups_user_id_d0013979_fk_Users_id"
            references public."Users"
            deferrable initially deferred,
    group_id integer not null,
    constraint "Users_groups_user_id_group_id_590dc796_uniq"
        unique (user_id, group_id)
);

create table public."Users_user_permissions"
(
    id            bigint generated by default as identity
        primary key,
    user_id       bigint  not null
        constraint "Users_user_permissions_user_id_c976b39e_fk_Users_id"
            references public."Users"
            deferrable initially deferred,
    permission_id integer not null,
    constraint "Users_user_permissions_user_id_permission_id_f5781f04_uniq"
        unique (user_id, permission_id)
);

create table public."CodePassword"
(
    id          bigint generated by default as identity
        primary key,
    code        varchar(10)              not null,
    expire_date timestamp with time zone not null,
    created_at  timestamp with time zone not null,
    user_id     bigint                   not null
        constraint "CodePassword_user_id_7daaba9f_fk_Users_id"
            references public."Users"
            deferrable initially deferred
);

create table public."Email Verifications"
(
    id          bigint generated by default as identity
        primary key,
    new_email   varchar(254)             not null,
    code        varchar(10)              not null,
    expire_date timestamp with time zone not null,
    user_id     bigint                   not null
        unique
        constraint "Email Verifications_user_id_70ff4e85_fk_Users_id"
            references public."Users"
            deferrable initially deferred
);

create table public."Users Profile"
(
    id                                bigint generated by default as identity
        primary key,
    middle_name                       varchar(120),
    interface_language                varchar(10),
    timezone                          varchar(64),
    birth_date                        date,
    profile_edit_blocked              boolean                  not null,
    deactivation_time                 timestamp with time zone,
    days_to_delete_after_deactivation integer
        constraint "Users Profile_days_to_delete_after_deactivation_check"
            check (days_to_delete_after_deactivation >= 0),
    phone_number                      varchar(20),
    company                           varchar(100),
    updated_at                        timestamp with time zone not null,
    profile_photo                     varchar(100),
    user_id                           bigint                   not null
        unique
        constraint "Users Profile_user_id_b4db25d4_fk_Users_id"
            references public."Users"
            deferrable initially deferred
);

create table public."Categories"
(
    id                 bigint generated by default as identity
        primary key,
    created_at         timestamp with time zone not null,
    updated_at         timestamp with time zone not null,
    is_deleted         boolean                  not null,
    name               varchar(100)             not null,
    parent_category_id bigint
        constraint "Categories_parent_category_id_1d658d8f_fk_Categories_id"
            references public."Categories"
            deferrable initially deferred
);

create table public."Courses"
(
    id                             bigint generated by default as identity
        primary key,
    created_at                     timestamp with time zone not null,
    updated_at                     timestamp with time zone not null,
    is_deleted                     boolean                  not null,
    name                           varchar(100)             not null,
    description                    text                     not null,
    image                          varchar(100),
    deadline_to_finish_course      timestamp with time zone,
    block_course_after_deadline    boolean                  not null,
    is_certificated                boolean                  not null,
    free_order                     boolean                  not null,
    allow_teachers_to_manage_tasks boolean                  not null,
    is_active                      boolean                  not null,
    author_id                      bigint
        constraint "Courses_author_id_0f7e8b44_fk_Users_id"
            references public."Users"
            deferrable initially deferred,
    category_id                    bigint
        constraint "Courses_category_id_6ab783f6_fk_Categories_id"
            references public."Categories"
            deferrable initially deferred
);

create table public."Course Groups"
(
    id                   bigint generated by default as identity
        primary key,
    created_at           timestamp with time zone not null,
    updated_at           timestamp with time zone not null,
    is_deleted           boolean                  not null,
    name                 varchar(100)             not null,
    students_limit       integer
        constraint "Course Groups_students_limit_check"
            check (students_limit >= 0),
    days_of_week         jsonb                    not null,
    self_registration    boolean                  not null,
    registration_token   varchar(128)
        unique,
    token_expires_at     timestamp with time zone,
    token_validity_hours integer
        constraint "Course Groups_token_validity_hours_check"
            check (token_validity_hours >= 0),
    token_validity_days  integer
        constraint "Course Groups_token_validity_days_check"
            check (token_validity_days >= 0),
    is_active            boolean                  not null,
    course_id            bigint                   not null
        constraint "Course Groups_course_id_7cf44eb8_fk_Courses_id"
            references public."Courses"
            deferrable initially deferred
);

create table public."Course Enrollments"
(
    id            bigint generated by default as identity
        primary key,
    role          varchar(20)              not null,
    enrolled_date timestamp with time zone not null,
    course_id     bigint                   not null
        constraint "Course Enrollments_course_id_cbca7dfe_fk_Courses_id"
            references public."Courses"
            deferrable initially deferred,
    user_id       bigint                   not null
        constraint "Course Enrollments_user_id_c6a18e45_fk_Users_id"
            references public."Users"
            deferrable initially deferred,
    group_id      bigint                   not null
        constraint "Course Enrollments_group_id_11b7a9b2_fk_Course Groups_id"
            references public."Course Groups"
            deferrable initially deferred,
    constraint uniq_user_group_role
        unique (user_id, group_id, role)
);

create table public."Tasks"
(
    id                               bigint generated by default as identity
        primary key,
    created_at                       timestamp with time zone not null,
    updated_at                       timestamp with time zone not null,
    is_deleted                       boolean                  not null,
    number                           integer
        constraint "Tasks_number_check"
            check (number >= 0),
    name                             varchar(100)             not null,
    description                      text                     not null,
    video                            varchar(100),
    image                            varchar(100),
    file                             varchar(100),
    enable_context_menu_for_students boolean                  not null,
    allow_resubmitting_task          boolean                  not null,
    course_id                        bigint                   not null
        constraint "Tasks_course_id_b979e73f_fk_Courses_id"
            references public."Courses"
            deferrable initially deferred,
    created_by_id                    bigint                   not null
        constraint "Tasks_created_by_id_b7a713c7_fk_Users_id"
            references public."Users"
            deferrable initially deferred
);

create table public."Chat_Rooms"
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    is_deleted boolean                  not null,
    is_active  boolean                  not null,
    course_id  bigint
        constraint "Chat_Rooms_course_id_79d1b9ea_fk_Courses_id"
            references public."Courses"
            deferrable initially deferred,
    student_id bigint                   not null
        constraint "Chat_Rooms_student_id_140a48aa_fk_Users_id"
            references public."Users"
            deferrable initially deferred,
    teacher_id bigint                   not null
        constraint "Chat_Rooms_teacher_id_2809d281_fk_Users_id"
            references public."Users"
            deferrable initially deferred,
    constraint "Chat_Rooms_teacher_id_student_id_6cbee984_uniq"
        unique (teacher_id, student_id)
);

create table public."Chat_Messages"
(
    id           bigint generated by default as identity
        primary key,
    created_at   timestamp with time zone not null,
    updated_at   timestamp with time zone not null,
    is_deleted   boolean                  not null,
    content      text                     not null,
    is_read      boolean                  not null,
    file         varchar(100),
    chat_room_id bigint                   not null
        constraint "Chat_Messages_chat_room_id_3f97bc8e_fk_Chat_Rooms_id"
            references public."Chat_Rooms"
            deferrable initially deferred,
    sender_id    bigint                   not null
        constraint "Chat_Messages_sender_id_154cd70c_fk_Users_id"
            references public."Users"
            deferrable initially deferred
);

create table public."Answers"
(
    id                bigint generated by default as identity
        primary key,
    created_at        timestamp with time zone not null,
    updated_at        timestamp with time zone not null,
    is_deleted        boolean                  not null,
    description       text                     not null,
    status            varchar(20)              not null,
    plagiarism_status varchar(32)              not null,
    extracted_text    text                     not null,
    analyzed_at       timestamp with time zone,
    task_id           bigint                   not null
        constraint "Answers_task_id_a4d4c121_fk_Tasks_id"
            references public."Tasks"
            deferrable initially deferred,
    user_id           bigint                   not null
        constraint "Answers_user_id_049750b2_fk_Users_id"
            references public."Users"
            deferrable initially deferred,
    constraint "Answers_user_id_task_id_e18a34e0_uniq"
        unique (user_id, task_id)
);

create table public.submissions_answerfile
(
    id            bigint generated by default as identity
        primary key,
    created_at    timestamp with time zone not null,
    updated_at    timestamp with time zone not null,
    is_deleted    boolean                  not null,
    file          varchar(100),
    original_name varchar(255),
    size          integer
        constraint submissions_answerfile_size_check
            check (size >= 0),
    content_type  varchar(100),
    answer_id     bigint                   not null
        constraint "submissions_answerfile_answer_id_86106bdf_fk_Answers_id"
            references public."Answers"
            deferrable initially deferred
);

create table public."Grades"
(
    id            bigint generated by default as identity
        primary key,
    created_at    timestamp with time zone not null,
    updated_at    timestamp with time zone not null,
    is_deleted    boolean                  not null,
    score         integer,
    feedback_text text,
    max_score     integer                  not null,
    answer_id     bigint                   not null
        unique
        constraint "Grades_answer_id_3aa395bb_fk_Answers_id"
            references public."Answers"
            deferrable initially deferred,
    graded_by_id  bigint                   not null
        constraint "Grades_graded_by_id_1e653996_fk_Users_id"
            references public."Users"
            deferrable initially deferred
);

create table public."Log_entry"
(
    id          bigint generated by default as identity
        primary key,
    timestamp   timestamp with time zone not null,
    level       varchar(30)              not null,
    logger_name varchar(255)             not null,
    message     text                     not null,
    pathname    varchar(500),
    line_no     integer,
    exception   text
);

create table public."Notifications"
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp with time zone not null,
    updated_at  timestamp with time zone not null,
    is_deleted  boolean                  not null,
    title       varchar(100)             not null,
    content     text                     not null,
    feedback    text,
    is_read     boolean                  not null,
    receiver_id bigint                   not null
        constraint "Notifications_receiver_id_bed975d5_fk_Users_id"
            references public."Users"
            deferrable initially deferred,
    sender_id   bigint
        constraint "Notifications_sender_id_b39735f8_fk_Users_id"
            references public."Users"
            deferrable initially deferred
);

create table public.plagiarism_plagiarismreport
(
    id               bigint generated by default as identity
        primary key,
    created_at       timestamp with time zone not null,
    updated_at       timestamp with time zone not null,
    is_deleted       boolean                  not null,
    similarity_score double precision         not null,
    flagged          boolean                  not null,
    review_status    varchar(32)              not null,
    reviewed_at      timestamp with time zone,
    review_note      text                     not null,
    reviewed_by_id   bigint
        constraint "plagiarism_plagiarismreport_reviewed_by_id_899b82b3_fk_Users_id"
            references public."Users"
            deferrable initially deferred,
    submission_a_id  bigint                   not null
        constraint "plagiarism_plagiaris_submission_a_id_b0448461_fk_Answers_i"
            references public."Answers"
            deferrable initially deferred,
    submission_b_id  bigint                   not null
        constraint "plagiarism_plagiaris_submission_b_id_fe8a9796_fk_Answers_i"
            references public."Answers"
            deferrable initially deferred,
    constraint unique_plagiarism_report_pair
        unique (submission_a_id, submission_b_id),
    constraint plagiarism_report_no_self_compare
        check (NOT (submission_a_id = submission_b_id))
);